---
name: Terraform Apply

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  test-job:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'Terraform Plan Update')
    runs-on: ubuntu-latest
    steps:
      - name: Output Text
        run: echo "This is a test job."
